# 工作流名称
name: Build Dylib on Push

# 触发条件：当有代码推送到主分支时触发
on:
  push:
    branches: [ "main", "master" ] # 适配主分支的不同名称
  workflow_dispatch: # 允许手动触发

jobs:
  # 任务名称
  build:
    # 运行环境：使用最新的macOS系统
    runs-on: macos-latest

    steps:
      # 第一步：检出（下载）你的仓库代码到虚拟机
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 第二步：执行编译
      - name: Compile the dylib using Makefile
        run: make

      # 第三步：上传编译产物
      - name: Upload compiled dylib as artifact
        uses: actions/upload-artifact@v4
        with:
          # 上传文件的名称
          name: ColorHook-Dylib
          # 要上传的文件路径
          path: ColorHook.dylib
