# 工作流名称
name: Build Self-Contained Dylib

# 触发条件
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. 执行编译
      - name: Compile the dylib
        run: make

      # 3. 上传编译产物
      - name: Upload dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: ColorHook-Dylib
          path: ColorHook.dylib
